<script src="{{ asset("js/jquery-1.11.1.min.js") }}"></script>
<script src="{{ asset("js/bootstrap.min.js") }}"></script>
<script src="{{ asset("js/chart.min.js") }}"></script>
<script src="{{ asset("js/chart-data.js") }}"></script>
<script src="{{ asset("js/easypiechart.js") }}"></script>
<script src="{{ asset("js/easypiechart-data.js") }}"></script>
<script src="{{ asset("js/bootstrap-datepicker.js") }}"></script>
<script src="{{ asset("vendor/izi-toast/dist/js/iziToast.min.js") }}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="{{ asset("js/custom.js") }}"></script>
<script src="{{ asset("/js/app.js") }}"></script>
